accounts/urls.py
from django.urls import path
from accounts.views import HomePage,signup,login
from django.contrib.auth.views import LogoutView



app_name="accounts"

urlpatterns = [
    path('', HomePage.as_view(),name="home"),
    path('signup/',signup,name="signup"),
    path('login/',login,name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
]

e_wallet/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('wallet/',include('wallet.urls')),
]


if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wallet/urls.py
from django.urls import path
from wallet.views import withdrow,deposit#transfer

app_name="wallet"

urlpatterns = [
    path('withdrow/', withdrow,name="withdrow"),
    path('deposit/',deposit,name="deposit"),
    # path('transfer/',transfer,name="transfer"),
]

accounts/models.py
from django.db import models

wallet/models.py
from django.db import models,IntegrityError
from decimal import Decimal
from django.contrib.auth.models import User


class InsufficientBalance(IntegrityError):
	"""Raised when a wallet has insufficient balance to
    run an operation.
    We're subclassing from :mod:`django.db.IntegrityError`
    so that it is automatically rolled-back during django's
    transaction lifecycle.
	"""

class Wallet(models.Model):
    # We should reference to the AUTH_USER_MODEL so that
    # when this module is used and a different User is used,
    # this would still work out of the box.
    #
    # See 'Referencing the User model' [1]
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # This stores the wallet's current balance. Also acts
    # like a cache to the wallet's balance as well.
    current_balance = models.DecimalField(max_digits=25, default=0, decimal_places=2)
    # The date/time of the creation of this wallet.
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

   


class Transaction(models.Model):
    # The wallet that holds this transaction.
    wallet = models.ForeignKey(Wallet,on_delete=models.CASCADE)

    # The value of this transaction.
    value = models.DecimalField(max_digits=6, decimal_places=2)

    # The value of the wallet at the time of this
    # transaction. Useful for displaying transaction
    # history.
    running_balance = models.DecimalField(max_digits=6, decimal_places=2)

    # The date/time of the creation of this transaction.
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
    	return str(self.wallet)

accounts/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView,TemplateView
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login
from wallet.models import Wallet,Transaction


class HomePage(TemplateView):
	template_name = "base.html"
	def get_context_data(self,*args,**kwargs):
		context = super(HomePage,self).get_context_data(**kwargs)
		context['current_balance'] =  Wallet.objects.all()
		return context

def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/')
	else:
		form = UserCreationForm()
		return render(request,"accounts/signup.html",{"form":form})


def login(request):
	if request.method=='POST':
	    username = request.POST['username']
	    password = request.POST['password']
	    user = authenticate(request, username=username, password=password)
	    if user is not None:
	        auth_login(request, user)
	        return redirect('/')
	    else:
	    	return render(request,'accounts/login.html')
	else:
		return render(request,'accounts/login.html')

wallet/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from wallet.models import Wallet,Transaction
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
import re
from decimal import Decimal


@login_required
def withdrow(request):
	user = request.user
	if request.method =='POST':
		value = request.POST.get('amount')
		try:
			wallet = Wallet.objects.get(user=user)
		except:
			wallet = 0
		if int(value)>wallet.current_balance:
			context = {
				"balance":wallet,
				"error":"Insufficient funds"
			}
			return render(request,'wallet/withdraw.html',context)
		else:
			wallet = Wallet.objects.get(user=user)
			balance = wallet.current_balance - int(value)
			Wallet.objects.filter(user=user).update(current_balance=balance)
			context = {
			"balance":wallet
			}
			return redirect('/wallet/withdrow/')#render(request,'wallet/withdraw.html',context)
	else:
		wallet = Wallet.objects.get(user=user)
		context = {
			"balance":wallet
		}
		return render(request,'wallet/withdraw.html',context)


@login_required
def deposit(request):
	user = request.user
	if request.method=='POST':
		try:
			value = request.POST.get('amount')
			wallet = Wallet.objects.get(user=user)
			total_amount =wallet.current_balance+int(value)
			Wallet.objects.filter(user=user).update(current_balance=total_amount)
			context ={
				"balance":wallet
			}
			return redirect('/wallet/deposit/')
		except:
			total_amount = request.POST.get('amount')
			Wallet.objects.filter(user=user).update(current_balance=total_amount)
			context ={
				"balance":wallet
			}
			return redirect('/wallet/deposit/')#render(request,'wallet/deposit.html',context)
	else:
		wallet = Wallet.objects.get(user=user)
		context = {

			"balance":wallet
		}
		return render(request,'wallet/deposit.html',context)


# @login_required
# def transfer(request):
# 	return render(request,'wallet/transfer.html')

# 	

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
  <h2>Login</h2>
  <form action="/login/" method="POST">{% csrf_token %}
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="text" class="form-control" id="username" placeholder="Enter username" name="username">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="password">
    </div>
    
     <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>

{% endblock content %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MyWallet</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  
<ul class="navbar-nav ">
    <li class="nav-item active">
      <a class="nav-link" href="#">MyWallet</a>
    </li>
{% if user.is_authenticated %}
   {% block balance %}
    <li class="nav-item justify-content-end">
      <a class="nav-link " href="#">Balance Rs.{% for i in current_balance %}{{ i.current_balance }} {% endfor %}</a>
    </li>

    {% endblock balance %}

{% endif %}

     <li class="nav-item justify-content-end">
      <a class="nav-link " href="{% url 'wallet:withdrow' %}">Withdraw</a>
    </li>

     <li class="nav-item justify-content-end">
      <a class="nav-link " href="{% url 'wallet:deposit' %}">Deposit</a>
    </li>



  </ul>

  <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link " href="{% url 'accounts:logout' %}">Welcome {{ user.username }}</a>
    </li>

    <li class="nav-item">
      <a class="nav-link " href="{% url 'accounts:logout' %}">Logout</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link " href="{% url 'accounts:login' %}">Login</a>
    </li>

    <li class="nav-item">
      <a class="nav-link " href="{% url 'accounts:signup' %}">Register</a>
    </li>

    {% endif %}

  </ul>
</nav>
{% block content %}

{% endblock content %}
</body>
</html>

templates/wallet/deposit.html
{% extends 'base.html' %}



{% block balance %}


 <li class="nav-item justify-content-end">
      <a class="nav-link " href="#">Balance Rs.{{ balance.current_balance }}</a>
    </li>

{% endblock balance %}





{% block content %}

<div class="container">
  <h2>Deposit</h2>
  <form action="/wallet/deposit/" method="POST">{% csrf_token %}
    
    {% if error %}
    <div class="alert alert-danger">
  <strong>!</strong> {{ error }}
</div>
    {% endif %}
    <div class="form-group">
      <label for="amount">Amount:</label>
      <input type="integer" class="form-control" id="pwd" placeholder="Enter amount" name="amount">
    </div>
    
     <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>

{% endblock content %}

templates/wallet/transfer.html
{% extends 'base.html' %}



{% block balance %}


 <li class="nav-item justify-content-end">
      <a class="nav-link " href="#">Balance Rs.{{ balance.current_balance }}</a>
    </li>

{% endblock balance %}




<h1> Comming Soon</h1>

{% block content %}

<div class="container">
  <h2>Transfer</h2>
  <form action="/wallet/deposit/" method="POST">{% csrf_token %}
    
    {% if error %}
    <div class="alert alert-danger">
  <strong>!</strong> {{ error }}
</div>
    {% endif %}
    <div class="form-group">
      <label for="amount">Amount:</label>
      <input type="integer" class="form-control" id="pwd" placeholder="Enter amount" name="amount">
    </div>
    
     <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>

{% endblock content %}

templates/wallet/withdraw.html
{% extends 'base.html' %}



{% block balance %}


 <li class="nav-item justify-content-end">
      <a class="nav-link " href="#">Balance Rs.{{ balance.current_balance }}</a>
    </li>

{% endblock balance %}





{% block content %}

<div class="container">
  <h2>Withdraw</h2>
  <form action="/wallet/withdrow/" method="POST">{% csrf_token %}
    
    {% if error %}
    <div class="alert alert-danger">
  <strong>!</strong> {{ error }}
</div>
    {% endif %}
    <div class="form-group">
      <label for="amount">Amount:</label>
      <input type="integer" class="form-control" id="pwd" placeholder="Enter amount" name="amount">
    </div>
    
     <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>

{% endblock content %}